# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.crowdreach.co.uk	
title: CrowdReach
email: contact@crowdreach.co.uk
description: > # "Helping you to market and crowdfund innovative products "

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
